/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/update/updateBook`; params?: Router.UnknownInputParams; } | { pathname: `/update/[id]`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cart` | `/cart`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/categories` | `/categories`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Test` | `/Test`; params?: Router.UnknownInputParams; } | { pathname: `/auth/forgetPassword`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownInputParams; } | { pathname: `/screens/about`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Admin`; params?: Router.UnknownInputParams; } | { pathname: `/screens/cardDetails`; params?: Router.UnknownInputParams; } | { pathname: `/screens/search`; params?: Router.UnknownInputParams; } | { pathname: `/screens/wishlist`; params?: Router.UnknownInputParams; } | { pathname: `/author/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/book/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/update/updateBook`; params?: Router.UnknownOutputParams; } | { pathname: `/update/[id]`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/cart` | `/cart`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/categories` | `/categories`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Test` | `/Test`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/forgetPassword`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/about`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Admin`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/cardDetails`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/search`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/wishlist`; params?: Router.UnknownOutputParams; } | { pathname: `/author/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/book/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/update/updateBook${`?${string}` | `#${string}` | ''}` | `/update/[id]${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/cart${`?${string}` | `#${string}` | ''}` | `/cart${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/categories${`?${string}` | `#${string}` | ''}` | `/categories${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Test${`?${string}` | `#${string}` | ''}` | `/Test${`?${string}` | `#${string}` | ''}` | `/auth/forgetPassword${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | `/auth/signup${`?${string}` | `#${string}` | ''}` | `/screens/about${`?${string}` | `#${string}` | ''}` | `/screens/Admin${`?${string}` | `#${string}` | ''}` | `/screens/cardDetails${`?${string}` | `#${string}` | ''}` | `/screens/search${`?${string}` | `#${string}` | ''}` | `/screens/wishlist${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/update/updateBook`; params?: Router.UnknownInputParams; } | { pathname: `/update/[id]`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cart` | `/cart`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/categories` | `/categories`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Test` | `/Test`; params?: Router.UnknownInputParams; } | { pathname: `/auth/forgetPassword`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownInputParams; } | { pathname: `/screens/about`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Admin`; params?: Router.UnknownInputParams; } | { pathname: `/screens/cardDetails`; params?: Router.UnknownInputParams; } | { pathname: `/screens/search`; params?: Router.UnknownInputParams; } | { pathname: `/screens/wishlist`; params?: Router.UnknownInputParams; } | `/author/${Router.SingleRoutePart<T>}` | `/book/${Router.SingleRoutePart<T>}` | { pathname: `/author/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/book/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
