/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/about`; params?: Router.UnknownInputParams; } | { pathname: `/authorList`; params?: Router.UnknownInputParams; } | { pathname: `/bookList`; params?: Router.UnknownInputParams; } | { pathname: `/cart`; params?: Router.UnknownInputParams; } | { pathname: `/categories`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownInputParams; } | { pathname: `/components/AuthorCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/AuthorDetails`; params?: Router.UnknownInputParams; } | { pathname: `/components/BookCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/BookDetails`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/profile/wishlist`; params?: Router.UnknownInputParams; } | { pathname: `/book/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/about`; params?: Router.UnknownOutputParams; } | { pathname: `/authorList`; params?: Router.UnknownOutputParams; } | { pathname: `/bookList`; params?: Router.UnknownOutputParams; } | { pathname: `/cart`; params?: Router.UnknownOutputParams; } | { pathname: `/categories`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/components/AuthorCard`; params?: Router.UnknownOutputParams; } | { pathname: `/components/AuthorDetails`; params?: Router.UnknownOutputParams; } | { pathname: `/components/BookCard`; params?: Router.UnknownOutputParams; } | { pathname: `/components/BookDetails`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/wishlist`; params?: Router.UnknownOutputParams; } | { pathname: `/book/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/about${`?${string}` | `#${string}` | ''}` | `/authorList${`?${string}` | `#${string}` | ''}` | `/bookList${`?${string}` | `#${string}` | ''}` | `/cart${`?${string}` | `#${string}` | ''}` | `/categories${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | `/auth/signup${`?${string}` | `#${string}` | ''}` | `/components/AuthorCard${`?${string}` | `#${string}` | ''}` | `/components/AuthorDetails${`?${string}` | `#${string}` | ''}` | `/components/BookCard${`?${string}` | `#${string}` | ''}` | `/components/BookDetails${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/profile/wishlist${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/about`; params?: Router.UnknownInputParams; } | { pathname: `/authorList`; params?: Router.UnknownInputParams; } | { pathname: `/bookList`; params?: Router.UnknownInputParams; } | { pathname: `/cart`; params?: Router.UnknownInputParams; } | { pathname: `/categories`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownInputParams; } | { pathname: `/components/AuthorCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/AuthorDetails`; params?: Router.UnknownInputParams; } | { pathname: `/components/BookCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/BookDetails`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/profile/wishlist`; params?: Router.UnknownInputParams; } | `/book/${Router.SingleRoutePart<T>}` | { pathname: `/book/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
